#Application URL
#url=https://staging.paysecure.net/
#url=https://newmodules2.choicepay.ca/
url=https://test4.paymentsclub.net/

#Browser Configuration
browser =chrome

#Credentials

#username=nitendra
#password=Ridhima@270216

username=sagarchippa
password=Sagar@123

#ImplicitWait (in seconds)
implicitWait =30

#ExplicitWait
explicitWait =30

#database
datasource.url=jdbc:mysql://172.31.88.8:3306/PGS?serverTimezone=UTC&useServerPrepStmts=false&rewriteBatchedStatements=true
datasource.driverClassName=com.mysql.cj.jdbc.Driver
datasource.username=PGS
datasource.collection=customerTransaction
datasource.password=PGSReady321@

merchantName=RohitM
MerchantName=Gouris
MN=gouris
BankName=paysafe
BankMid=paysafeMid

